name: CI

on:
    push:
        branches:
            - develop
            - 'feature/**'
    pull_request:
        branches:
            - develop
            - 'feature/**'

jobs:
    build:
        name: Build on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                include:
                    - os: ubuntu-latest
                      platform_name: Linux
                    - os: macos-latest
                      platform_name: macOS
                    - os: windows-latest
                      platform_name: Windows

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Ninja (Ubuntu)
              if: matrix.os == 'ubuntu-latest'
              run: sudo apt-get update && sudo apt-get install -y ninja-build

            - name: Install Ninja (macOS)
              if: matrix.os == 'macos-latest'
              run: brew install ninja

            - name: Install Ninja (Windows)
              if: matrix.os == 'windows-latest'
              run: choco install ninja

            - name: Configure CMake
              run: cmake -GNinja -B_build -DCMAKE_BUILD_TYPE=Release

            - name: Build
              run: cmake --build _build --config Release

            - name: Get current date
              id: date
              run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
              shell: bash

            - name: Create artifact directory
              run: |
                  mkdir -p artifact/${{ matrix.platform_name }}
                  cp _build/libkstring.* artifact/${{ matrix.platform_name }}/ 2>/dev/null || true
                  cp _build/kstring.* artifact/${{ matrix.platform_name }}/ 2>/dev/null || true
              shell: bash

            - name: Create archive
              run: tar -czf kstring-build${{ github.run_number }}-${{ steps.date.outputs.date }}.tar.gz -C artifact .
              shell: bash

            - name: Upload Build Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: kstring-build${{ github.run_number }}-${{ steps.date.outputs.date }}
                  path: kstring-build${{ github.run_number }}-${{ steps.date.outputs.date }}.tar.gz
                  retention-days: 7
